# Generated by Django 2.2 on 2021-02-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('subcategory', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('real_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('score', models.FloatField(default=3.5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
