# Generated by Django 2.2 on 2021-02-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('CATEGORY1', 'Marketing Digital'), ('CATEGORY2', 'Manualidades'), ('CATEGORY3', 'Ilustración y Dibujo'), ('CATEGORY4', 'Lifestyle'), ('CATEGORY5', 'Marketing Digital'), ('CATEGORY6', 'Video'), ('CATEGORY7', 'Negocios'), ('CATEGORY8', 'Fotografia'), ('CATEGORY9', 'Diseño'), ('CATEGORY10', 'Escritura'), ('CATEGORY11', 'Animación & 3D')], max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='subcategory',
            field=models.CharField(choices=[('SUBCATEGORY1', 'Marketing Digital'), ('SUBCATEGORY2', 'Bordado y costura'), ('SUBCATEGORY3', 'Ilustración Digital'), ('SUBCATEGORY4', 'Lifestyle'), ('SUBCATEGORY5', 'Producción'), ('SUBCATEGORY6', 'Locución'), ('SUBCATEGORY7', 'Innovación'), ('SUBCATEGORY8', 'Liderazgo'), ('SUBCATEGORY9', 'Fundamentos de fotografía'), ('SUBCATEGORY10', 'Publicidad'), ('SUBCATEGORY11', 'Postproducción'), ('SUBCATEGORY12', 'Dibujo'), ('SUBCATEGORY13', 'Branding'), ('SUBCATEGORY14', 'Retoque Fotográfico'), ('SUBCATEGORY15', 'Escritura'), ('SUBCATEGORY16', 'Ventas'), ('SUBCATEGORY17', 'Data'), ('SUBCATEGORY18', 'Animación 2D')], max_length=150),
        ),
    ]
