# Generated by Django 2.2 on 2021-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210228_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Marketing Digital', 'Marketing Digital'), ('Manualidades', 'Manualidades'), ('Ilustración y Dibujo', 'Ilustración y Dibujo'), ('Lifestyle', 'Lifestyle'), ('Marketing Digital', 'Marketing Digital'), ('Video', 'Video'), ('Negocios', 'Negocios'), ('Fotografia', 'Fotografia'), ('Diseño', 'Diseño'), ('Escritura', 'Escritura'), ('Animación & 3D', 'Animación & 3D')], max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Introductorio', 'Introductorio'), ('Intermedio', 'Intermedio'), ('Completo', 'Completo'), ('Avanzado', 'Avanzado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='subcategory',
            field=models.CharField(choices=[('Marketing Digital', 'Marketing Digital'), ('Bordado y costura', 'Bordado y costura'), ('Ilustración Digital', 'Ilustración Digital'), ('Lifestyle', 'Lifestyle'), ('Producción', 'Producción'), ('Locución', 'Locución'), ('Innovación', 'Innovación'), ('Liderazgo', 'Liderazgo'), ('Fundamentos de fotografía', 'Fundamentos de fotografía'), ('Publicidad', 'Publicidad'), ('Postproducción', 'Postproducción'), ('Dibujo', 'Dibujo'), ('Branding', 'Branding'), ('Retoque Fotográfico', 'Retoque Fotográfico'), ('Escritura', 'Escritura'), ('Ventas', 'Ventas'), ('Data', 'Data'), ('Animación 2D', 'Animación 2D')], max_length=150),
        ),
    ]
