# Generated by Django 2.2 on 2021-02-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210228_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.IntegerField(default=0),
        ),
    ]
